
library(epimod)

downloadContainers()


model_generation(net_fname = "./Net/SIR.PNPRO")


###  Sensitivity analysis

## Simple version where only the transition rates vary.
sensitivity<-sensitivity_analysis(n_config = 200,
                                  parameters_fname = "Input/Functions_list.csv", 
                                  solver_fname = "Net/SIR.solver",
                                  reference_data = "Input/reference_data.csv",
                                  distance_measure_fname = "Rfunction/msqd.R" ,
                                  target_value_fname = "Rfunction/Target.R" ,
                                  f_time = 7*10, # weeks
                                  s_time = 1, # days      
                                  parallel_processors = 2
                                  )

##############################
## Let draw the orbits characterizing the phase-space
##############################

library(ggplot2)

load("./Results/results_sensitivity_analysis/SIR-sensitivity.RData")
load("./Results/results_sensitivity_analysis/ranking_SIR-sensitivity.RData")
reference <- as.data.frame(t(read.csv("Input/reference_data.csv",
                                      header = FALSE,
                                      sep = "")))

# Then, we read all the trajectories generated saving them in a list called
# ListTraces. List that will be rewritten as a data frame in order to use ggplot.
# ConfigID represents the initial condition associated to each trajectory,
# which was generated by using the function implemented in the file Functions.R .

listFile<-list.files("./Results/results_sensitivity_analysis/",
                     pattern = ".trace")

configID<-t(sapply(1:length(listFile),
                   function(x){
                       return(c(x,config[[1]][[x]][[3]]))
                   }) )

id.traces<-as.numeric(gsub("[^[:digit:].]", "",listFile) )

ListTraces<-lapply(id.traces,
                   function(x){
                       trace.tmp=read.csv(paste0(
                           "./Results/results_sensitivity_analysis/SIR-sensitivity-",
                           x,
                           ".trace"), sep = "")
                       trace.tmp=data.frame(trace.tmp,ID=rank[which(rank[,2]==x),1])
                       return(trace.tmp)
                   })

rank2<-lapply(id.traces,
                   function(x){
                       recovery<-config[[1]][[x]][[3]]
                       infection<-config[[2]][[x]][[3]]
                       rnk.tmp=data.frame(ID=x,distance = rank$measure[which(rank[,2]==x)],rec_rate=recovery, inf_rate=infection)
                       return(rnk.tmp)
                   })

rank2 <- do.call("rbind", rank2)
traces <- do.call("rbind", ListTraces)

ggplot( )+
    geom_line(data=traces,
              aes(x=Time/7,y=I,group=ID,col=ID))+
    geom_line(data=reference,
              aes(x=V1/7,y=V3),
              col="red")+
    theme(axis.text=element_text(size=18),
        axis.title=element_text(size=20,face="bold"),
        legend.text=element_text(size=18),
        legend.title=element_text(size=20,face="bold"),
        legend.position="right",
        legend.key.size = unit(1.3, "cm"),
        legend.key.width = unit(1.3,"cm") )+
    labs(x="Weeks", y="I",col="Distance")

ggplot( )+
    geom_line(data=traces,
              aes(x=Time/7,y=S,group=ID,col=ID))+
    geom_line(data=reference,
              aes(x=V1/7,y=V2),
              col="red")+
    theme(axis.text=element_text(size=18),
        axis.title=element_text(size=20,face="bold"),
        legend.text=element_text(size=18),
        legend.title=element_text(size=20,face="bold"),
        legend.position="right",
        legend.key.size = unit(1.3, "cm"),
        legend.key.width = unit(1.3,"cm") )+
    labs(x="Weeks", y="S",col="Distance")

ggplot( )+
    geom_line(data=traces,
              aes(x=Time/7,y=R,group=ID,col=ID))+
    geom_line(data=reference,
              aes(x=V1/7,y=V4),
              col="red")+
    theme(axis.text=element_text(size=18),
        axis.title=element_text(size=20,face="bold"),
        legend.text=element_text(size=18),
        legend.title=element_text(size=20,face="bold"),
        legend.position="right",
        legend.key.size = unit(1.3, "cm"),
        legend.key.width = unit(1.3,"cm") )+
    labs(x="Weeks", y="R",col="Distance")




ggplot(rank2,aes(x=rec_rate,y=inf_rate,col=(distance-min(distance))/max(distance)))+
  geom_point(size=3)+
  theme(axis.text=element_text(size=18),
        axis.title=element_text(size=20,face="bold"),
        legend.text=element_text(size=18),
        legend.title=element_text(size=20,face="bold")) +
  labs(title="",col="distance",x= "Recovery",y="Infection")+
  scale_colour_gradientn(colours = c("black","deepskyblue2","cyan"),
                         values= c(0,.000002,1),
                         breaks=c(0,.999),
                         labels=c("min","max"))

## Version where only the PRCC is calculated
sensitivity<-sensitivity_analysis(n_config = 100,
                                  parameters_fname = "Input/Functions_list.csv", 
                                  functions_fname = "Rfunction/Functions.R",
                                  solver_fname = "Net/SIR.solver",
                                  target_value_fname = "Rfunction/Target.R" ,
                                  parallel_processors = 1,
                                  f_time = 7*10, # weeks
                                  s_time = 1 # days
                                  )

## Version where only the ranking is calculated
sensitivity<-sensitivity_analysis(n_config = 100,
                                  parameters_fname = "Input/Functions_list.csv", 
                                  functions_fname = "Rfunction/Functions.R",
                                  solver_fname = "Net/SIR.solver",
                                  reference_data = "Input/reference_data.csv",
                                  distance_measure_fname = "Rfunction/msqd.R" ,
                                  parallel_processors = 1,
                                  f_time = 7*10, # weeks
                                  s_time = 1 # days
                                  )

## Complete and more complex version where all the parameters for calculating
## the PRCC and the ranking are considered, and the initial conditions vary too.

sensitivity<-sensitivity_analysis(n_config = 100,
                                  parameters_fname = "Input/Functions_list2.csv", 
                                  functions_fname = "Rfunction/Functions.R",
                                  solver_fname = "Net/SIR.solver",
                                  reference_data = "Input/reference_data.csv",
                                  distance_measure_fname = "Rfunction/msqd.R" ,
                                  target_value_fname = "Rfunction/Target.R" ,
                                  parallel_processors = 2,
                                  f_time = 7*10, # weeks
                                  s_time = 1 # days
                                  )

### Calibration analysis


model_calibration(parameters_fname = "Input/Functions_list_Calibration.csv",
                  functions_fname = "Rfunction/FunctionCalibration.R",
                  solver_fname = "Net/SIR.solver",
                  reference_data = "Input/reference_data.csv",
                  distance_measure_fname = "Rfunction/msqd.R" ,
                  f_time = 7*10, # weeks
                  s_time = 1, # days
                  # Vectors to control the optimization
                  ini_v = c(0.15,0.00015),
                  ub_v = c(0.2, 0.0002),
                  lb_v = c(0.1, 0.0001),
                  max.call = 50
                  )


##############################
## Let draw the orbits characterizing the phase-space
##############################

library(ggplot2)

load("./Results/results_model_calibration/calibration_optim.RData")
load("./Results/results_model_calibration/calibration.RData")
reference <- as.data.frame(t(read.csv("Input/reference_data.csv",
                                      header = FALSE,
                                      sep = "")))
calibration_optim_trace <-read.csv("./Results/results_model_calibration/calibration_optim-trace.csv",sep = "")


# Then, we read all the trajectories generated saving them in a list called
# ListTraces. List that will be rewritten as a data frame in order to use ggplot.
# ConfigID represents the initial condition associated to each trajectory,
# which was generated by using the function implemented in the file Functions.R .

listFile<-list.files("./Results/results_model_calibration/",
                     pattern = ".trace")

id.traces<-calibration_optim_trace$id

ListTraces<-lapply(id.traces,
                   function(x){
                       trace.tmp=read.csv(paste0(
                           "./Results/results_model_calibration/calibration-",
                           x,
                           ".trace"), sep = "")
                       trace.tmp=data.frame(trace.tmp,ID=calibration_optim_trace$distance[which(calibration_optim_trace$id==x)])
                       return(trace.tmp)
                   })

traces <- do.call("rbind", ListTraces)

ggplot( )+
    geom_line(data=traces,
              aes(x=Time/7,y=I,group=ID,col=ID))+
    geom_line(data=reference,
              aes(x=V1/7,y=V3),
              col="red")+
    theme(axis.text=element_text(size=18),
        axis.title=element_text(size=20,face="bold"),
        legend.text=element_text(size=18),
        legend.title=element_text(size=20,face="bold"),
        legend.position="right",
        legend.key.size = unit(1.3, "cm"),
        legend.key.width = unit(1.3,"cm") )+
    labs(x="Weeks", y="I",col="Distance")

ggplot( )+
    geom_line(data=traces,
              aes(x=Time/7,y=S,group=ID,col=ID))+
    geom_line(data=reference,
              aes(x=V1/7,y=V2),
              col="red")+
    theme(axis.text=element_text(size=18),
        axis.title=element_text(size=20,face="bold"),
        legend.text=element_text(size=18),
        legend.title=element_text(size=20,face="bold"),
        legend.position="right",
        legend.key.size = unit(1.3, "cm"),
        legend.key.width = unit(1.3,"cm") )+
    labs(x="Weeks", y="S",col="Distance")

ggplot( )+
    geom_line(data=traces,
              aes(x=Time/7,y=R,group=ID,col=ID))+
    geom_line(data=reference,
              aes(x=V1/7,y=V4),
              col="red")+
    theme(axis.text=element_text(size=18),
        axis.title=element_text(size=20,face="bold"),
        legend.text=element_text(size=18),
        legend.title=element_text(size=20,face="bold"),
        legend.position="right",
        legend.key.size = unit(1.3, "cm"),
        legend.key.width = unit(1.3,"cm") )+
    labs(x="Weeks", y="R",col="Distance")


### Model Analysis


model_analysis(out_fname = "model_analysis",
               solver_fname = "Net/SIR.solver",
               parameters_fname = "Results/Functions_list_ModelAnalysis.csv",
               f_time = 7*10, # weeks
               s_time = 1
               )

