library(ggplot2)

SensitivityPlot <-function(rank=T,folder){
	load(paste0(folder,"SIR_age_vaccination-sensitivity.RData"))
	# Then, we read all the trajectories generated saving them in a list called
	# ListTraces. List that will be rewritten as a data frame in order to use ggplot.
	# ConfigID represents the initial condition associated to each trajectory,
	# which was generated by using the function implemented in the file Functions.R .

	listFile<-list.files(folder,
											 pattern = ".trace")

	configID<-t(sapply(1:length(listFile),
										 function(x){
										 	return(c(x,config[[1]][[x]][[3]]))
										 }) )

	id.traces<-as.numeric(gsub("[^[:digit:].]", "",listFile) )

	if(rank){
		load(paste0(folder,"ranking_SIR_age_vaccination-sensitivity.RData"))
	}else{
		rank <- data.frame(measure = 0 , id = paste0("SIR_age_vaccination-sensitivity-",
																								 id.traces,
																								 ".trace"))
	}

	ListTraces<-lapply(id.traces,
										 function(x){
										 	trace.tmp=read.csv(paste0(
										 		folder,"/SIR_age_vaccination-sensitivity-",
										 		x,
										 		".trace"), sep = "")
										 	trace.tmp=data.frame(trace.tmp,ID= x,
										 											 rank = rank[which(rank[,2]==paste0("SIR_age_vaccination-sensitivity-",
										 											 																	 x,
										 											 																	 ".trace")),1])
										 	return(trace.tmp)
										 })

	traces <- do.call("rbind", ListTraces)

	plI_a1<-ggplot( )+
		geom_line(data=traces,
							aes(x=Time,y=I_a1,group=ID,col=rank))+
		theme(axis.text=element_text(size=18),
					axis.title=element_text(size=20,face="bold"),
					legend.text=element_text(size=18),
					legend.title=element_text(size=20,face="bold"),
					legend.position="right",
					legend.key.size = unit(1.3, "cm"),
					legend.key.width = unit(1.3,"cm") )+
		labs(x="Weeks", y="I_a1",col="Distance")

	plI_a2<-ggplot( )+
		geom_line(data=traces,
							aes(x=Time,y=I_a2,group=ID,col=rank))+
		theme(axis.text=element_text(size=18),
					axis.title=element_text(size=20,face="bold"),
					legend.text=element_text(size=18),
					legend.title=element_text(size=20,face="bold"),
					legend.position="right",
					legend.key.size = unit(1.3, "cm"),
					legend.key.width = unit(1.3,"cm") )+
		labs(x="Weeks", y="I_a2",col="Distance")

	plS_a1<-ggplot( )+
		geom_line(data=traces,
							aes(x=Time,y=S_a1,group=ID,col=rank))+
		theme(axis.text=element_text(size=18),
					axis.title=element_text(size=20,face="bold"),
					legend.text=element_text(size=18),
					legend.title=element_text(size=20,face="bold"),
					legend.position="right",
					legend.key.size = unit(1.3, "cm"),
					legend.key.width = unit(1.3,"cm") )+
		labs(x="Weeks", y="S_a1",col="Distance")

	plS_a2<-ggplot( )+
		geom_line(data=traces,
							aes(x=Time,y=S_a2,group=ID,col=rank))+
		theme(axis.text=element_text(size=18),
					axis.title=element_text(size=20,face="bold"),
					legend.text=element_text(size=18),
					legend.title=element_text(size=20,face="bold"),
					legend.position="right",
					legend.key.size = unit(1.3, "cm"),
					legend.key.width = unit(1.3,"cm") )+
		labs(x="Weeks", y="S_a2",col="Distance")

	plR_a1<-ggplot( )+
		geom_line(data=traces,
							aes(x=Time,y=R_a1,group=ID,col=rank))+
		theme(axis.text=element_text(size=18),
					axis.title=element_text(size=20,face="bold"),
					legend.text=element_text(size=18),
					legend.title=element_text(size=20,face="bold"),
					legend.position="right",
					legend.key.size = unit(1.3, "cm"),
					legend.key.width = unit(1.3,"cm") )+
		labs(x="Weeks", y="R_a1",col="Distance")

	plR_a2<-ggplot( )+
		geom_line(data=traces,
							aes(x=Time,y=R_a2,group=ID,col=rank))+
		theme(axis.text=element_text(size=18),
					axis.title=element_text(size=20,face="bold"),
					legend.text=element_text(size=18),
					legend.title=element_text(size=20,face="bold"),
					legend.position="right",
					legend.key.size = unit(1.3, "cm"),
					legend.key.width = unit(1.3,"cm") )+
		labs(x="Weeks", y="R_a2",col="Distance")

	plV_a1<-ggplot( )+
		geom_line(data=traces,
							aes(x=Time,y=V_a1,group=ID,col=rank))+
		theme(axis.text=element_text(size=18),
					axis.title=element_text(size=20,face="bold"),
					legend.text=element_text(size=18),
					legend.title=element_text(size=20,face="bold"),
					legend.position="right",
					legend.key.size = unit(1.3, "cm"),
					legend.key.width = unit(1.3,"cm") )+
		labs(x="Weeks", y="V_a1",col="Distance")

	plV_a2<-ggplot( )+
		geom_line(data=traces,
							aes(x=Time,y=V_a2,group=ID,col=rank))+
		theme(axis.text=element_text(size=18),
					axis.title=element_text(size=20,face="bold"),
					legend.text=element_text(size=18),
					legend.title=element_text(size=20,face="bold"),
					legend.position="right",
					legend.key.size = unit(1.3, "cm"),
					legend.key.width = unit(1.3,"cm") )+
		labs(x="Weeks", y="V_a2",col="Distance")

	return(list(TrajS_a1 =plS_a1, TrajS_a2 =plS_a2,TrajI_a1 =plI_a1,TrajI_a2 =plI_a2,TrajR_a1 =plR_a1,TrajR_a2 =plR_a2,TrajV_a1 =plV_a1,TrajV_a2 =plV_a2))
}

