library(epimod)
downloadContainers()

model.generation(net_fname = "./Net/SIR.PNPRO")

#Execute model_analysis to derive the model behaviors
model.analysis(solver_fname = "SIR.solver",
							 i_time = 1,
               f_time = 100, # days
               s_time = 1)

#Plot the result computed by the model analysis
#Source the code in ModelAnalysisPlot.R This file can be downloaded here:
#https://github.com/qBioTurin/SIR/blob/MasterLesson/Rfunction/ModelAnalysisPlot.R
source("./Rfunction/ModelAnalysisPlot.R")
#Execute the function ModelAnalysisPlot
AnalysisPlots = ModelAnalysisPlot("SIR_analysis/SIR-analysis-1.trace",
																	Stoch = F,
																	print = T)


#Execute model_analysis to derive the model behaviors using SSA
model.analysis("SIR.solver",
               solver_type = "SSA",
               f_time = 100,
               s_time = 1,
               n_run = 500)

#Execute the function ModelAnalysisPlot
AnalysisPlots = ModelAnalysisPlot("./SIR_analysis/SIR-analysis-1.trace", Stoch = TRUE)


#Execute model_analysis to derive the model behaviors updating parameters
model.analysis("SIR.solver",
               f_time=100,
               s_time=1,
               parameters_fname = "./Input/Functions_list_ModelAnalysis.csv")

#Execute the function ModelAnalysisPlot
AnalysisPlots = ModelAnalysisPlot("./SIR_analysis/SIR-analysis-1.trace")


#Execute model_analysis to derive the model behaviors using SSA
model.analysis(solver_fname = "SIR.solver",
               solver_type = "SSA",
               f_time = 100,
               s_time = 1,
               n_run = 500,
               parameters_fname = "./Input/Functions_list_ModelAnalysis.csv")

#Execute the function ModelAnalysisPlot
AnalysisPlots = ModelAnalysisPlot("./SIR_analysis/SIR-analysis-1.trace", Stoch = TRUE)


#Execute model_calibration to derive those parameter values fitting an input data.
#Observe that the data are generated by the model with 0.04 and 0.0004.
model.calibration(solver_fname = "./Net/SIR.solver",
                  parameters_fname = "./Input/Functions_list_Calibration.csv",
                  functions_fname = "./Rfunction/FunctionCalibration.R",
                  reference_data = "./Input/reference_data.csv",
                  distance_measure = "mse",
                  i_time = 1,
                  f_time = 100, # days
                  s_time = 1, # day
                  # Vectors to control the optimization
                  ini_v = c(0.035,0.00035),
                  ub_v = c(0.05, 0.0005),
                  lb_v = c(0.025, 0.00025),
                  max.time = 1)

#Plot the result computed by the model calibration
#Source the code in CalibrationPlot.R This file can be download here:
#https://raw.githubusercontent.com/qBioTurin/SIR/MasterLesson/Rfunction/CalibrationPlot.R
source("./Rfunction/CalibrationPlot.R")
#Execute the function ModelAnalysisPlot
CalibrationPlots = calibration.plot("SIR_calibration/SIR", "./Input/reference_data.csv")
