library(ggplot2)

SensitivityPlot <-function(rank=T,folder, scd_folder){
  #Changed the folder in which is contained the .RData file
  load(paste0(scd_folder,"SIR-analysis.RData"))  
  # Then, we read all the trajectories generated saving them in a list called
  # ListTraces. List that will be rewritten as a data frame in order to use ggplot.
  # ConfigID represents the initial condition associated to each trajectory,
  # which was generated by using the function implemented in the file Functions.R .
  
  listFile<-list.files(scd_folder,
                       pattern = ".trace")
  
  configID<-t(sapply(1:length(listFile),
                     function(x){
                       return(c(x,config[[1]][[x]][[3]]))
                     }) )
  
  id.traces<-as.numeric(gsub("[^[:digit:].]", "",listFile) )
  
  if(rank){
    load(paste0(folder,"ranking_SIR-sensitivity.RData"))
  }else{
    rank <- data.frame(measure = 0 , id = id.traces)
  }
  
  reference <- as.data.frame(read.csv("Input/reference_data.csv",
                                      header = FALSE,
                                      sep = ""))
  
  
  
  ListTraces<-lapply(id.traces,
                     function(x){
                       trace.tmp=read.csv(paste0(
                         scd_folder,"SIR-analysis-",
                         x,
                         ".trace"), sep = "")
                       trace.tmp=data.frame(trace.tmp,ID= x,
                                            rank = rank[which(rank[,2]==paste0("SIR-analysis-",
                                                                               x,
                                                                               ".trace")),1])
                       return(trace.tmp)
                     })
  
  rank2<-lapply(id.traces,
                function(x){
                  recovery<-config[[4]][[x]][[3]]
                  infection<-config[[5]][[x]][[3]]
                  rnk.tmp=data.frame(ID=x,distance = rank[which(rank[,2]==paste0("SIR-analysis-",
                                                                                 x,
                                                                                 ".trace")),1],
                                     rec_rate=recovery, inf_rate=infection)
                  return(rnk.tmp)
                })
  
  
  rank2 <- do.call("rbind", rank2)
  traces <- do.call("rbind", ListTraces)
  
  plI<-ggplot( )+
    geom_line(data=traces,
              aes(x=Time,y=I,group=ID,col=rank))+
    geom_line(data=reference,
              aes(x=V1,y=V3),
              col="red")+
    theme(axis.text=element_text(size=18),
          axis.title=element_text(size=20,face="bold"),
          legend.text=element_text(size=18),
          legend.title=element_text(size=20,face="bold"),
          legend.position="right",
          legend.key.size = unit(1.3, "cm"),
          legend.key.width = unit(1.3,"cm") )+
    labs(x="Weeks", y="I",col="Distance")
  
  plS<-ggplot( )+
    geom_line(data=traces,
              aes(x=Time,y=S,group=ID,col=rank))+
    geom_line(data=reference,
              aes(x=V1,y=V2),
              col="red")+
    theme(axis.text=element_text(size=18),
          axis.title=element_text(size=20,face="bold"),
          legend.text=element_text(size=18),
          legend.title=element_text(size=20,face="bold"),
          legend.position="right",
          legend.key.size = unit(1.3, "cm"),
          legend.key.width = unit(1.3,"cm") )+
    labs(x="Weeks", y="S",col="Distance")
  
  plR<-ggplot( )+
    geom_line(data=traces,
              aes(x=Time,y=R,group=ID,col=rank))+
    geom_line(data=reference,
              aes(x=V1,y=V4),
              col="red")+
    theme(axis.text=element_text(size=18),
          axis.title=element_text(size=20,face="bold"),
          legend.text=element_text(size=18),
          legend.title=element_text(size=20,face="bold"),
          legend.position="right",
          legend.key.size = unit(1.3, "cm"),
          legend.key.width = unit(1.3,"cm") )+
    labs(x="Weeks", y="R",col="Distance")
  
  
  ColMax<-max((rank2$distance-min(rank2$distance))/max(rank2$distance))
  
  pl<-ggplot(rank2,aes(x=rec_rate,y=inf_rate,col=(distance-min(distance))/max(distance)))+
    geom_point(size=3)+
    theme(axis.text=element_text(size=18),
          axis.title=element_text(size=20,face="bold"),
          legend.text=element_text(size=18),
          legend.title=element_text(size=20,face="bold")) +
    labs(title="",col="distance",x= "Recovery",y="Infection")+
    scale_colour_gradientn(colours = c("black","deepskyblue2","cyan"),
                           values= c(0,.002,1),
                           breaks=c(0,ColMax),
                           labels=c("min","max"))
  
  return(list(TrajS =plS,TrajI =plI,TrajR =plR,Points = pl))
}

